apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/DiogoP98/argocd-test
        revision: main
        directories:
          - path: applications-helm/*
  template:
    metadata:
      name: '{{path.basename}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/DiogoP98/argocd-test
        targetRevision: main
        path: applications-helm/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true