apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-prd
  labels:
    app: demo-app-prd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-app-prd
  template:
    metadata:
      labels:
        app: demo-app-prd
    spec:
      containers:
      - name: demo-app-prd
        image: nginx:latest
        ports:
        - containerPort: 80
